// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAg65WZADH-n-HAoHeHZxgxOxmK7IyIi0Q',
    appId: '1:528722351527:android:0390fa918ce0e78457d282',
    messagingSenderId: '528722351527',
    projectId: 'toubibplus-bdd-e790a',
    storageBucket: 'toubibplus-bdd-e790a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUj2cFAyKKK1T_fL_08qnP1wPIwaQ5G5s',
    appId: '1:528722351527:ios:37f355d6fa7dbbff57d282',
    messagingSenderId: '528722351527',
    projectId: 'toubibplus-bdd-e790a',
    storageBucket: 'toubibplus-bdd-e790a.appspot.com',
    iosClientId: '528722351527-jqtp1gt3jajcrac5088at11r93cu0dbv.apps.googleusercontent.com',
    iosBundleId: 'com.toubibplus.toubibplus',
  );

}